all: ../../lib/MainController.o ../../lib/GestureQueue.o 

../../lib/MainController.o: MainController.cpp
	g++ -g -c -Wall -Wextra -I.. -std=c++11 MainController.cpp -o ../../lib/MainController.o

../../lib/GestureQueue.o: GestureQueue.cpp
	g++ -g -c -Wall -Wextra -I.. -std=c++11 GestureQueue.cpp -o ../../lib/GestureQueue.o
