

all: 
	g++ --std=c++11 -o test ../../src/FileSystem/FileManager.cpp unitTests.c -lstdc++fs
	./test

compile:
	g++ --std=c++11 -c -Wall -Wextra  ../../src/FileSystem/FileManager.cpp -lstdc++fs
	rm *.o
