all: ../../lib/GestureCapture.o ../../lib/GestureEvent.o 

../../lib/GestureCapture.o: GestureCapture.cpp
	g++ -g -c -Wall -Wextra -I.. -I../../include -std=c++11 GestureCapture.cpp -o ../../lib/GestureCapture.o

../../lib/GestureEvent.o: GestureEvent.cpp
	g++ -g -c -Wall -Wextra -I.. -I../../include  -std=c++11 GestureEvent.cpp -o ../../lib/GestureEvent.o
